AllCops:
  RunRailsCops: true

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'config/application.rb'
